function O2 = read_O2_props(filename,vmax);
%IMPORTFILE Import data from a text file
%  O2_ENERGY = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  O2_ENERGY = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  O2_Energy = importfile("/Users/spkearn/Desktop/CARSFT_Matlab_Dev/O2_model/table_s1_16o16o_energy_levels.txt", [6, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-Mar-2024 19:33:55

%% Input handling

% If dataLines is not specified, define defaults

dataLines = [6, Inf];

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["v", "N", "J", "K", "Energycm1", "Unccm1", "Degeneracy", "Var8"];
opts.SelectedVariableNames = ["v", "N", "J", "K", "Energycm1", "Unccm1", "Degeneracy"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, "Var8", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var8", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "v", "TrimNonNumeric", true);
opts = setvaropts(opts, "v", "ThousandsSeparator", ",");

% Import the data
O2data = readtable(filename, opts);

%% Convert to output type
O2data = table2array(O2data);
indx = find(O2data(:,1) <= vmax+1);

O2.v = O2data(indx,1);
O2.N = O2data(indx,2);
O2.J = O2data(indx,3);
O2.term = O2data(indx,5);
O2.g = O2data(indx,7);

end